server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  servlet:
    multipart:
      enabled: false
  mvc:
    view:
       prefix: classpath:/templates/
       suffix: .html
    static-path-pattern: /static/**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    username: root
    password: rr998xhz1997
  thymeleaf:
      mode: HTML5 #模板的模式不配置默认是HTML模式
      encoding: utf-8
      servlet:
        content-type: text/html
      cache: false  #设置是否存在缓存
girl:
  old: 21
  cutsize: C

#boy:
#  old: 23
#  cutsize: C

